---
site_name: Odd One Out
site_url: https://example.com/
# Note: For nesting navigation, the parent CANNOT have a page associated with
# it. In order to have the parent clickable, include an "index.md" for it. See
See: https://github.com/mkdocs/mkdocs/issues/1139#issuecomment-281483739
nav:
  - Home: index.md
  - About:
    - Privacy Policy: privacy-policy.md
    - Terms of Service: terms-of-service.md
    - Third Party Services: third-party-services.md
theme:
  name: material
  palette:
    - scheme: slate
  favicon: assets/images/favicon.png
  logo: assets/logo.png
  features:
    - tabs
    - navigation.indexes
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - tables
